# Generated by Django 2.1.4 on 2018-12-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distro',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distro',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
