# Generated by Django 2.1.4 on 2018-12-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0002_auto_20181229_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(blank=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('photo', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('notes', models.TextField(max_length=400)),
                ('last_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.AddField(
            model_name='distro',
            name='workspace_url',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
