# Generated by Django 2.1.4 on 2018-12-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distro', '0003_auto_20181229_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='distro',
            name='workspace_id',
            field=models.IntegerField(null=True),
        ),
    ]
